name: Lint
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download clang-tidy
        run: sudo apt install clang-tidy

      - name: Run clang-tidy
        run: |
          chmod +x ./scripts/lint.sh
          ./scripts/lint.sh
