name: Lint
on: [push]
jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download clang-tidy
        run: |
          echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-14 main" | sudo tee -a /etc/apt/sources.list
          echo "deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy-14 main" | sudo tee -a /etc/apt/sources.list
          sudo apt update
          sudo apt install clang-tidy-14
          clang-tidy --version

  Lint-No-CUDA:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run clang-tidy
        run: |
          chmod +x ./scripts/lint.sh
          ./scripts/lint.sh

  Lint-CUDA:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup CUDA
        uses: Jimver/cuda-toolkit@v0.2.7
        id: cuda-toolkit

      - name: Verify CUDA installation
        run: |
          echo ">>> Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
          nvcc -V

      - name: Run clang-tidy
        run: |
          chmod +x ./scripts/lint.sh
          ./scripts/lint.sh