name: Lint
on: [push]
jobs:
  Style-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download clang-format
        run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          sudo apt install clang-format-18
          sudo apt install clang
          clang-format-18 --version
          

      - name: Run clang-format
        run: |
          chmod +x ./scripts/format.sh
          ./scripts/format.sh -p clang-format-18

  Lint-No-CUDA:
    needs: Style-Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download clang-tidy
        run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          sudo apt install clang-tidy-18
          clang-tidy-18 --version

      - name: Run clang-tidy
        run: |
          chmod +x ./scripts/lint.sh
          ./scripts/lint.sh -p clang-tidy-18 -a None

  Lint-No-CUDA-AVX:
    needs: Style-Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download clang-tidy
        run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          sudo apt install clang-tidy-18
          clang-tidy-18 --version

      - name: Run clang-tidy
        run: |
          chmod +x ./scripts/lint.sh
          ./scripts/lint.sh -p clang-tidy-18 -a AVX2

  Lint-CUDA:
    needs: Style-Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download clang-tidy
        run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          sudo apt install clang-tidy-18
          sudo apt install clang-14
          clang-tidy-18 --version
          clang --version

      - name: Setup CUDA
        uses: Jimver/cuda-toolkit@v0.2.15
        id: cuda-toolkit
        with:
          cuda: '12.1'

      - name: Verify CUDA installation
        run: |
          echo ">>> Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
          nvcc -V

      - name: Run clang-tidy
        run: |
          chmod +x ./scripts/lint.sh
          ./scripts/lint.sh -p clang-tidy-18