name: Lint
on: [push]
jobs:
  Style-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download clang-format
        run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          sudo apt install clang-format-15
          clang-format-15 --version

      - name: Run clang-format
        run: |
          chmod +x ./scripts/format.sh
          ./scripts/format.sh -p clang-format-15

  Lint-No-CUDA:
    needs: Style-Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download clang-tidy
        run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          sudo apt install clang-tidy-15
          clang-tidy-15 --version

      - name: Run clang-tidy
        run: |
          chmod +x ./scripts/lint.sh
          ./scripts/lint.sh -p clang-tidy-15 -a None

  Lint-No-CUDA-AVX:
    needs: Style-Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download clang-tidy
        run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          sudo apt install clang-tidy-15
          clang-tidy-15 --version

      - name: Run clang-tidy
        run: |
          chmod +x ./scripts/lint.sh
          ./scripts/lint.sh -p clang-tidy-15 -a AVX2

  Lint-CUDA:
    needs: Style-Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download clang-tidy
        run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          sudo apt install clang-tidy-15
          clang-tidy-15 --version

      - name: Setup CUDA
        uses: Jimver/cuda-toolkit@v0.2.7
        id: cuda-toolkit

      - name: Verify CUDA installation
        run: |
          echo ">>> Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
          nvcc -V

      - name: Install lower version of GNU
        run: |
          sudo apt update
          sudo apt install gcc-9.4=9.4.0-1ubuntu1~22.04 g++-9.4=9.4.0-1ubuntu1~22.04

      - name: Run clang-tidy
        run: |
          chmod +x ./scripts/lint.sh
          ./scripts/lint.sh -p clang-tidy-15
        env:
          CC: gcc-9.4
          CXX: g++-9.4