name: Style Check
on: [push]
jobs:
  Style-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Remove old version of clang-format
        run: apt remove clang-format

      # Get clang-format version 14.0.0 file from https://github.com/ElectricRCAircraftGuy
      # Steps taken from https://stackoverflow.com/questions/20756924/how-can-i-install-clang-format-in-ubuntu
      - name: Download clang-format
        run: wget https://github.com/ElectricRCAircraftGuy/eRCaGuy_CodeFormatter/raw/main/bin/clang-format

      - name: Setup clang-format
        run: |
            chmod +x clang-format
            mkdir -p ~/bin
            mv clang-format ~/bin
            clang-format --version

      - name: Run clang-format
        run: |
            chmod +x ./scripts/format.sh
            ./scripts/format.sh
