name: Style Check
on: [push]
jobs:
  Style-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download clang-format
        run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          sudo apt install clang-format-14
          clang-format-14 --version

      - name: Run clang-format
        run: |
            chmod +x ./scripts/format.sh
            ./scripts/format.sh -p clang-format-14
